### ISSUE TITLE
error  Async arrow function has no 'await' expression  require-await

### ISSUE THREAD

**Issue by lylehenderson** [ellucian-developer/experience-ethos-examples#10]
experience-ethos-examples-main\account-details-extension> npm run deploy-dev
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> account-details-extension@1.0.5 deploy-dev
> webpack --progress --mode development --env verbose --env upload

6% setup before compile WebpackExperienceValidatorPluginValidating extension definition ...
Extension config validated
6% setup before compile WebpackExperienceUploadPluginExtension upload token validated
37% building 2/4 entries 4/4 dependencies 1/3 modulesBrowserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
99% done plugins WebpackExperienceUploadPlugin
Upload aborted due to compilation errors and/or warnings

assets by status 1.75 MiB [cached] 2 assets
runtime modules 2.09 KiB 11 modules
modules by path ./node_modules/ 271 KiB 67 modules
modules by path ./src/ 47.6 KiB
  modules by path ./src/i18n/ 4.17 KiB 4 modules
  modules by path ./src/page/*.jsx 12.7 KiB 2 modules
  modules by path ./src/data/*.js 15.7 KiB 2 modules
  3 modules
modules by path external "@ellucian/react-design-system/ 126 bytes
  external "@ellucian/react-design-system/core" 42 bytes [built] [code generated]
  external "@ellucian/react-design-system/core/styles/tokens" 42 bytes [built] [code generated]
  external "@ellucian/react-design-system/core/styles" 42 bytes [built] [code generated]
external "react" 42 bytes [built] [code generated]
external "react-intl" 42 bytes [built] [code generated]
external "prop-types" 42 bytes [built] [code generated]
external "react-dom" 42 bytes [built] [code generated]

ERROR in ./src/context/account-details.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

.\experience-ethos-examples-main\account-details-extension\src\context\account-details.js
  48:23  error  Async arrow function has no 'await' expression  require-await

✖ 1 problem (1 error, 0 warnings)

 @ ./src/cards/AccountDetails.jsx 13:0-87 95:27-44 292:42-64

**Comment by lylehenderson** [comment]
Same error with the Today-classes-extensiton

src\cards\TodayClassesDash.jsx
  85:19  error  Async arrow function has no 'await' expression  require-await

✖ 1 problem (1 error, 0 warnings)


webpack 5.4.0 compiled with 1 error and 26 warnings in 7291 ms

**Comment by lylehenderson** [comment]
Attempted to revert commit dc49295d2e111ab18b94b08a376b45dcedda5057 in my local copy.
just the await commands.
It compiles, with 26 warnings, but doesn't deploy.

**Comment by ellucianBret** [comment]
This is being taken care of in the latest updates. It is partially done. The rest will soon follow.
