### ISSUE TITLE
 Something Went Wrong, Contact your Administrator

### ISSUE THREAD

**Issue by baltimore1920** [ellucian-developer/experience-ethos-examples#14]
I've installed this to our TEST environment and the card didn't have much on it other than selection boxes.  I clicked on Chart or Table (whichever wasn't selected by default) and now I get the following:

Something Went Wrong
Contact your Administrator

Thoughts?  Is there a log that I can see any information with what may be going wrong? 

Thank you!

CRorer
Saint Xavier University

**Comment by ellucianBret** [comment]
Can you elaborate on what you installed? There are several examples in this repo. The one with a chart is a tool to watch the data load times of the other examples.

Thx,
Bret

**Comment by baltimore1920** [comment]
Thanks Bret!  I literally only installed this API Dashboard.  I was doing them one at a time and skipping the Banner ones.  Sorry that I wasn't clearer.  When I opened the issue, I was under experience-ethos-examples/api-dashboard/extension/README.md, so I thought it would be obvious that I was working with the api-dashboard.  Seems it posted to the main branch though.

I'll install the others and see if that helps.

Thanks again!

Christine

**Comment by baltimore1920** [comment]
It's working now that I installed another extension.

Thanks!

Christine
