### ISSUE TITLE
Instructor's Classes Extension - what URL do we put in for "Instructor Classes URL"?

### ISSUE THREAD

**Issue by baltimore1920** [ellucian-developer/experience-ethos-examples#15]
It's part of the configuration and I'm unsure which URL it is asking for?

Thanks!

Christine
Saint Xavier University

**Comment by ellucianBret** [comment]
Christine,

I assume you are running the microservice locally? If so the URL will be http://localhost:3000/api

This is the base URL that you see in the console when you run the microservice locally.

Bret
