### ISSUE TITLE
Error running "npm run deploy-and-upload" on api-dashboard

### ISSUE THREAD

**Issue by iaryal** [ellucian-developer/experience-ethos-examples#23]
Hello: I am trying to test the api-dashboard card project and not able to run the command. I get the following error:

PS C:\Development-Ish\experience-ethos-examples-main> npm run deploy-and-upload
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Development-Ish\experience-ethos-examples-main/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Development-Ish\experience-ethos-examples-main\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by iaryal** [comment]
turns out package.json file is not in C:\Development-Ish\experience-ethos-examples-main which makes sense. But I ran the command from within API-Dashboard and still ran into this issue:

PS C:\Development-Ish\experience-ethos-examples-main\api-dashboard> npm run watch-and-upload
npm ERR! Missing script: "watch-and-upload"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by ellucianBret** [comment]
you need to change to the api-dashboard/extension directory.

Even though this one is just an extension, the folder structure in these examples is to put the Experience extension in a directory called extension. See the doc for details.

**Comment by iaryal** [comment]
Thank yoU!
